import { Be_Vietnam_Pro } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import ScreenSize from "./components/ScreenSize";

const be_vietnam_pro = Be_Vietnam_Pro({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Yumy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-background-50 text-text">
      <body className={be_vietnam_pro.className}>
        <ScreenSize />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
